# Generated by Django 5.0.6 on 2024-06-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('descryption', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
